web:
  restart: always
  ports:
    - "32542:32542"
  build: .
  volumes:
    - ".:/code"
  entrypoint: /code/start-web.sh
  links:
    - mysql
    - redis
  environment:
    - LARAVEL_ENV=local
    - REDIS_HOST=redis
    - VIRTUAL_HOST=laravel.example.com

worker:
  restart: always
  build: .
  volumes:
    - ".:/code"
  entrypoint: /code/start-worker.sh
  links:
    - mysql
    - redis
  environment:
    - LARAVEL_ENV=local
    - REDIS_HOST=redis

cron:
  restart: always
  build: .
  volumes:
    - ".:/code"
  entrypoint: /code/start-cron.sh
  links:
    - mysql
    - redis
  environment:
    - LARAVEL_ENV=local
    - REDIS_HOST=redis

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  env_file: ./app/.env
  environment:
    - MYSQL_ROOT_PASSWORD=SomePassword

redis:
  image: redis:2.8
  ports:
    - "6379:6379"
